---
# Timeout value after we which we give up on AppCloud operations that are long running.
# Within this value, we poll for completion status of the operations with the
# sleep interval between successive poll requests specified below.
timeout_secs: 60
job_timeout_secs: 30
sleep_secs: 1

simple_app:
  framework: "http://b20nine.com/unknown"
  memory: 128
  path: "assets/sinatra/hello_vcap"

simple_app2:
  framework: "http://b20nine.com/unknown"
  memory: 64
  path: "assets/sinatra/hello_vcap"

simple_app3:
  framework: "http://b20nine.com/unknown"
  memory: 64
  path: "assets/sinatra/hello_vcap"

tiny_java_app:
  framework: "java_web/1.0"
  memory: 128
  path: "assets/java_web/java_tiny_app/target"

simple_db_app:
  framework: "http://b20nine.com/unknown"
  memory: 128
  path: "assets/sinatra/simple_db_app"

redis_lb_app:
  framework: "http://b20nine.com/unknown"
  memory: 128
  path: "assets/sinatra/redis_lb_app"

env_test_app:
  framework: "http://b20nine.com/unknown"
  memory: 64
  path: "assets/sinatra/env_test_app"

broken_app:
  framework: "http://b20nine.com/unknown"
  memory: 64
  path: "assets/sinatra/broken_app"

rails3_app:
  framework: "rails/1.0"
  memory: 128
  path: "assets/rails3/rails3_app"

jpa_app:
  framework: "spring_web/1.0"
  memory: 512
  path: "assets/spring/jpa-guestbook/target"

hibernate_app:
  framework: "spring_web/1.0"
  memory: 512
  path: "assets/spring/hibernate-guestbook/target"

dbrails_app:
  framework: "rails/1.0"
  memory: 128
  path: "assets/rails3/dbrails_app"

dbrails_broken_app:
  framework: "rails/1.0"
  memory: 128
  path: "assets/rails3/dbrails_broken_app"

grails_app:
  framework: "grails/1.0"
  memory: 512
  path: "assets/grails/guestbook/target"

roo_app:
  framework: "spring_web/1.0"
  memory: 256
  path: "assets/spring/roo-guestbook/target"

mochiweb_test:
  framework: "otp_rebar"
  memory: 64
  path: "assets/mochiweb/mochiweb_test/rel/mochiweb_test"

simple-lift-app:
  framework: "lift/1.0"
  memory: 256
  path: "assets/lift/hello_lift/target"

lift-db-app:
  framework: "lift/1.0"
  memory: 256
  path: "assets/lift/lift-db-app/target"

tomcat-version-check-app:
  framework: "spring_web/1.0"
  memory: 128
  tomcat_version: "6.0.35"
  path: "assets/java_web/tomcat-version-check-app/target"

app_rails_version18:
  framework: "rails3"
  runtime: ruby18
  memory: 256
  path: "assets/rails3/app_rails_version"

app_rails_version19:
  framework: "rails3"
  runtime: ruby19
  memory: 256
  path: "assets/rails3/app_rails_version"

app_rails_service:
  framework: "rails/1.0"
  memory: 256
  path: "assets/rails3/app_rails_service"

app_rails_service_autoconfig:
  framework: "rails/1.0"
  memory: 256
  path: "assets/rails3/app_rails_service_autoconfig"

rails_autoconfig_disabled_by_file:
  framework: "rails/1.0"
  memory: 256
  path: "assets/rails3/autoconfig_disabled_by_file"

rails_autoconfig_disabled_by_gem:
  framework: "rails/1.0"
  memory: 256
  path: "assets/rails3/autoconfig_disabled_by_gem"

app_rack_service:
  framework: "rack"
  memory: 256
  path: "assets/rack/app_rack_service"

app_rack_service_autoconfig:
  framework: "rack"
  startup: "ruby app.rb"
  memory: 64
  path: "assets/rack/app_rack_service_autoconfig"

rack_autoconfig_ruby19:
  framework: "rack"
  startup: "ruby app.rb"
  memory: 64
  runtime: ruby19
  path: "assets/rack/autoconfig_ruby19"

rack_autoconfig_disabled_by_file:
  framework: "rack"
  startup: "ruby app.rb"
  memory: 64
  path: "assets/rack/autoconfig_disabled_by_file"

rack_autoconfig_disabled_by_gem:
  framework: "rack"
  startup: "ruby app.rb"
  memory: 64
  path: "assets/rack/autoconfig_disabled_by_gem"

app_sinatra_service:
  framework: "http://b20nine.com/unknown"
  memory: 256
  path: "assets/sinatra/app_sinatra_service"

app_sinatra_service2:
  framework: "http://b20nine.com/unknown"
  memory: 256
  path: "assets/sinatra/app_sinatra_service"

app_sinatra_service_autoconfig:
  framework: "http://b20nine.com/unknown"
  memory: 64
  path: "assets/sinatra/app_sinatra_service_autoconfig"

amqp_autoconfig:
  framework: "sinatra"
  memory: 64
  runtime: ruby19
  path: "assets/sinatra/amqp_autoconfig"

autoconfig_unsupported_versions:
  framework: "http://b20nine.com/unknown"
  memory: 64
  path: "assets/sinatra/autoconfig_unsupported_versions"

autoconfig_unsupported_carrot_version:
  framework: "http://b20nine.com/unknown"
  memory: 64
  path: "assets/sinatra/autoconfig_unsupported_carrot_version"

sinatra_autoconfig_disabled_by_file:
  framework: "http://b20nine.com/unknown"
  memory: 64
  path: "assets/sinatra/autoconfig_disabled_by_file"

sinatra_autoconfig_disabled_by_gem:
  framework: "http://b20nine.com/unknown"
  memory: 64
  path: "assets/sinatra/autoconfig_disabled_by_gem"

app_node_service:
  framework: "node"
  runtime: node
  memory: 512
  path: "assets/node/app_node_service"

app_node_dependencies04:
  framework: "node"
  runtime: node
  memory: 64
  path: "assets/node/node_dependencies04"

app_node_dependencies06:
  framework: "node"
  runtime: node06
  memory: 64
  path: "assets/node/node_dependencies06"

app_node_version04:
  framework: "node"
  runtime: node
  memory: 64
  path: "assets/node/app_node_version"

app_node_version06:
  framework: "node"
  runtime: node06
  memory: 64
  path: "assets/node/app_node_version"

app_spring_service:
  framework: "spring_web/1.0"
  memory: 512
  path: "assets/spring/app_spring_service/target"

my_test_app_env_test_app:
  framework: "http://b20nine.com/unknown"
  memory: 64
  path: "assets/sinatra/hello_vcap"

memcached_app:
  framework: "http://b20nine.com/unknown"
  memory: 64
  path: "assets/sinatra/memcached_app"

neo4j_app:
  framework: "http://b20nine.com/unknown"
  memory: 128
  path: "assets/sinatra/neo4j_app"

simple_wsgi_app:
  framework: "wsgi"
  memory: 64
  path: "assets/django/simple_wsgi_app"

wsgi_app_with_requirements:
  framework: "wsgi"
  memory: 64
  path: "assets/django/wsgi_app_with_requirements"

simple_django_app:
  framework: "django"
  memory: 64
  path: "assets/django/simple_django_app"

simple_php_app:
  framework: "php"
  memory: 64
  path: "assets/php/simple_php_app"

spring-env-app:
  framework: "spring_web/1.0"
  memory: 256
  path: "assets/spring/spring-env/target"

auto-reconfig-test-app:
  framework: "spring_web/1.0"
  memory: 512
  path: "assets/spring/auto-reconfig-test-app/target"

auto-reconfig-missing-deps-test-app:
  framework: "spring_web/1.0"
  memory: 256
  path: "assets/spring/auto-reconfig-missing-deps-test-app/target"

atmos_app:
  framework: "http://b20nine.com/unknown"
  memory: 256
  path: "assets/sinatra/atmos_app"

simple_kv_app:
  framework: "http://b20nine.com/unknown"
  memory: 64
  path: "assets/sinatra/simple_kv_app"

brokered_service_app:
  framework: "http://b20nine.com/unknown"
  memory: 64
  path: "assets/sinatra/brokered_service_app"

java_app_with_startup_delay:
  framework: "java_web/1.0"
  memory: 128
  path: "assets/java_web/app_with_startup_delay/target"

rails_console_test_app:
  framework: "rails3"
  memory: 256
  path: "assets/rails3/app_rails_service"

rails_console_19_test_app:
  framework: "rails3"
  memory: 256
  path: "assets/rails3/hello_vcap"
  runtime: ruby19

vblob_app:
  framework: "http://b20nine.com/unknown"
  memory: 256
  path: "assets/sinatra/app_sinatra_service"

service_quota_app:
  framework: "http://b20nine.com/unknown"
  startup: "ruby main.rb"
  memory: 512
  path: "assets/sinatra/app_sinatra_service_quota/"

standalone_ruby18_app:
  framework: "standalone"
  command: "bundle exec ruby main.rb -p $VCAP_APP_PORT"
  memory: 256
  runtime: ruby18
  path: "assets/standalone/ruby_app"

standalone_ruby19_app:
  framework: "standalone"
  command: "bundle exec ruby main.rb -p $VCAP_APP_PORT"
  memory: 256
  runtime: ruby19
  path: "assets/standalone/ruby_app"

standalone_simple_ruby18_app:
  framework: "standalone"
  command: "ruby simple.rb"
  memory: 256
  runtime: ruby18
  path: "assets/standalone/simple_ruby_app"
  no_url: true

standalone_simple_ruby18_quotes_app:
  framework: "standalone"
  command: "ruby \"simple.rb\""
  memory: 256
  runtime: ruby18
  path: "assets/standalone/simple_ruby_app"
  no_url: true

standalone_simple_ruby19_app:
  framework: "standalone"
  command: "ruby simple.rb"
  memory: 256
  runtime: ruby19
  path: "assets/standalone/simple_ruby_app"
  no_url: true

standalone_java_app:
  framework: "standalone"
  command: "bin/hello-cloud"
  runtime: java
  memory: 256
  path: "assets/standalone/java_app/target/appassembler"
  no_url: true

standalone_node_app:
  framework: "standalone"
  command: "node app.js"
  runtime: node
  memory: 64
  path: "assets/standalone/node_app"

standalone_node06_app:
  framework: "standalone"
  command: "node app.js"
  runtime: node06
  memory: 64
  path: "assets/standalone/node_app"

standalone_ruby18_autoconfig:
  framework: "standalone"
  command: "bundle exec ruby app.rb -p $VCAP_APP_PORT"
  runtime: ruby18
  memory: 64
  path: "assets/standalone/ruby_autoconfig"

standalone_ruby19_autoconfig:
  framework: "standalone"
  command: "bundle exec ruby app.rb -p $VCAP_APP_PORT"
  runtime: ruby19
  memory: 64
  path: "assets/standalone/ruby_autoconfig"

standalone_ruby_autoconfig_disabled_by_file:
  framework: "standalone"
  command: "bundle exec ruby app.rb -p $VCAP_APP_PORT"
  runtime: ruby18
  memory: 64
  path: "assets/standalone/ruby_autoconfig_disabled_by_file"

standalone_ruby_autoconfig_disabled_by_gem:
  framework: "standalone"
  command: "bundle exec ruby app.rb -p $VCAP_APP_PORT"
  runtime: ruby18
  memory: 64
  path: "assets/standalone/ruby_autoconfig_disabled_by_gem"

standalone_php_app:
  framework: "standalone"
  command: "php index.php"
  runtime: php
  memory: 64
  path: "assets/standalone/php_app"
  no_url: true

standalone_python_app:
  framework: "standalone"
  command: "python HelloWorld.py"
  runtime: python2
  memory: 64
  path: "assets/standalone/python_app"
  no_url: true

standalone_erlang_app:
  framework: "standalone"
  command: "erl -noshell -s helloworld start -s"
  runtime: erlangR14B02
  memory: 64
  path: "assets/standalone/erlang_app"
  no_url: true

broken_gem_app:
  framework: sinatra
  runtime: ruby18
  memory: 64
  path: "assets/sinatra/broken_gem_app"

play_computer_database_scala_app:
  framework: "play"
  memory: 128
  path: "assets/play/computer_database_scala/target"

play_todolist_app:
  framework: "play"
  memory: 128
  path: "assets/play/todolist/target"

play_zentasks_cf_by_name_app:
  framework: "play"
  memory: 128
  path: "assets/play/zentasks_cf_by_name/target"

play_zentasks_cf_by_type_app:
  framework: "play"
  memory: 128
  path: "assets/play/zentasks_cf_by_type/target"

play_computer_database_autoconfig_disabled_app:
  framework: "play"
  memory: 128
  path: "assets/play/computer_database_autoconfig_disabled/target"

play_todolist_with_cfruntime_app:
  framework: "play"
  memory: 128
  path: "assets/play/todolist_with_cfruntime/target"

play_computer_database_jpa_app:
  framework: "play"
  memory: 128
  path: "assets/play/computer_database_jpa/target"

play_computer_database_jpa_mysql_app:
  framework: "play"
  memory: 128
  path: "assets/play/computer_database_jpa_mysql/target"

play_computer_database_multi_dbs_app:
  framework: "play"
  memory: 128
  path: "assets/play/computer_database_multi_dbs/target"

play_computer_database_cf_by_name_app:
  framework: "play"
  memory: 128
  path: "assets/play/computer_database_cf_by_name/target"

play_computer_database_cf_by_type_app:
  framework: "play"
  memory: 128
  path: "assets/play/computer_database_cf_by_type/target"

javaee-namespace-app:
  framework: "spring_web/1.0"
  startup: "thin start"
  memory: 256
  path: "assets/spring/javaee-namespace-app/target"

auto-reconfig-annotation-app:
  framework: "spring_web/1.0"
  memory: 512
  path: "assets/spring/auto-reconfig-annotation-app/target"
