source "http://rubygems.org"

gem "json"
gem "httpclient"
gem "rake"
gem "rspec", "1.3.0"
gem "cucumber", "1.1.3"
gem "gherkin", "2.6.7"
gem "curb", "0.8.0"
gem "nokogiri"
gem "nats"
gem "rest-client"
gem "rubyzip", "~> 0.9.4"
gem "terminal-table"
gem "highline"
gem "vmc", ">= 0.3.17"
gem "parallel", "0.5.11"
gem "parallel_tests"
gem "caldecott", "~> 0.0.4"
