source "http://rubygems.org"

gem "json"
gem "httpclient"
gem "rake"
gem "rspec", "1.3.0"
gem "cucumber", "1.1.3"
gem "gherkin", "2.6.7"
gem "curb"
gem "nokogiri"
gem "nats"
gem "rest-client"
gem "rubyzip2"
gem "terminal-table"
gem "highline"
gem "vmc", ">= 0.3.13.beta.4"
gem "parallel_tests"
